import * as FileSystem from 'expo-file-system/legacy';
import * as Sharing from 'expo-sharing';
import * as Print from 'expo-print';
import { Platform, Alert } from 'react-native';

// Lock to prevent multiple share requests
let isSharing = false;

/**
 * Generates an HTML report of expenses and downloads it as a PDF
 */
export const downloadExpensesPDF = async (expenses) => {
    if (isSharing) return;
    if (!expenses || expenses.length === 0) {
        Alert.alert('No expenses to download');
        return;
    }

    isSharing = true;

    try {
        const rowsHTML = expenses.map(expense => `
            <tr>
                <td>${expense.date ? new Date(expense.date).toLocaleDateString() : ''}</td>
                <td>${expense.title}</td>
                <td>${expense.category}</td>
                <td>${expense.paymentMethod || '-'}</td>
                <td style="text-align: right; color: #dc2626;">₹${(expense.amount || 0).toLocaleString()}</td>
            </tr>
        `).join('');

        const totalAmount = expenses.reduce((sum, item) => sum + (parseFloat(item.amount) || 0), 0);

        const html = `
            <html>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
                <style>
                    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
                    h1 { text-align: center; margin-bottom: 5px; color: #0f172a; }
                    p.dates { text-align: center; color: #64748b; font-size: 14px; margin-bottom: 20px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                    th { background-color: #f1f5f9; text-align: left; padding: 10px; font-size: 12px; border-bottom: 2px solid #e2e8f0; }
                    td { padding: 10px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
                    .total-row td { border-top: 2px solid #0f172a; font-weight: bold; font-size: 16px; padding-top: 15px; }
                    .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #94a3b8; }
                </style>
            </head>
            <body>
                <h1>Expense Report</h1>
                <p class="dates">Generated on ${new Date().toLocaleString()}</p>
                
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Method</th>
                            <th style="text-align: right;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${rowsHTML}
                        <tr class="total-row">
                            <td colspan="4" style="text-align: right;">Total Expenses</td>
                            <td style="text-align: right; color: #dc2626;">₹${totalAmount.toLocaleString()}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="footer">
                    <p>Generated by Zilling App</p>
                </div>
            </body>
            </html>
        `;

        const { uri } = await Print.printToFileAsync({ html });

        if (Platform.OS === 'android' && FileSystem.StorageAccessFramework) {
            try {
                // The isSharing lock already guards the entry to this function,
                // which prevents multiple simultaneous permission requests from here.
                const permissions = await FileSystem.StorageAccessFramework.requestDirectoryPermissionsAsync();
                if (permissions.granted) {
                    const base64 = await FileSystem.readAsStringAsync(uri, { encoding: 'base64' });
                    const fileName = `Expenses_${new Date().getTime()}.pdf`;
                    const newUri = await FileSystem.StorageAccessFramework.createFileAsync(permissions.directoryUri, fileName, 'application/pdf');
                    await FileSystem.writeAsStringAsync(newUri, base64, { encoding: 'base64' });
                    Alert.alert('Success', 'PDF saved successfully');
                    return;
                }
            } catch (safError) {
                if (safError.message.includes("unfinished permission request")) {
                    console.warn('SAF Permission already pending:', safError);
                    Alert.alert("Permission Error", "A folder selection window is already open. Please complete or cancel it before trying again.");
                } else {
                    console.warn('SAF Error, falling back to Share:', safError);
                }
            }
        }

        // Fallback for iOS or if SAF fails/is denied
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('PDF Export Error:', error);
        Alert.alert('Failed to export PDF');
    } finally {
        isSharing = false;
    }
};

/**
 * Generates an HTML report of expenses and shares it as a PDF
 */
export const shareExpensesPDF = async (expenses) => {
    if (isSharing) return;
    if (!expenses || expenses.length === 0) {
        Alert.alert('No expenses to share');
        return;
    }

    isSharing = true;

    try {
        const rowsHTML = expenses.map(expense => `
            <tr>
                <td>${expense.date ? new Date(expense.date).toLocaleDateString() : ''}</td>
                <td>${expense.title}</td>
                <td>${expense.category}</td>
                <td>${expense.paymentMethod || '-'}</td>
                <td style="text-align: right; color: #dc2626;">₹${(expense.amount || 0).toLocaleString()}</td>
            </tr>
        `).join('');

        const totalAmount = expenses.reduce((sum, item) => sum + (parseFloat(item.amount) || 0), 0);

        const html = `
            <html>
            <head>
                <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0, user-scalable=no" />
                <style>
                    body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; padding: 20px; color: #333; }
                    h1 { text-align: center; margin-bottom: 5px; color: #0f172a; }
                    p.dates { text-align: center; color: #64748b; font-size: 14px; margin-bottom: 20px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
                    th { background-color: #f1f5f9; text-align: left; padding: 10px; font-size: 12px; border-bottom: 2px solid #e2e8f0; }
                    td { padding: 10px; border-bottom: 1px solid #f1f5f9; font-size: 13px; }
                    .total-row td { border-top: 2px solid #0f172a; font-weight: bold; font-size: 16px; padding-top: 15px; }
                    .footer { margin-top: 30px; text-align: center; font-size: 10px; color: #94a3b8; }
                </style>
            </head>
            <body>
                <h1>Expense Report</h1>
                <p class="dates">Generated on ${new Date().toLocaleString()}</p>
                
                <table>
                    <thead>
                        <tr>
                            <th>Date</th>
                            <th>Title</th>
                            <th>Category</th>
                            <th>Method</th>
                            <th style="text-align: right;">Amount</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${rowsHTML}
                        <tr class="total-row">
                            <td colspan="4" style="text-align: right;">Total Expenses</td>
                            <td style="text-align: right; color: #dc2626;">₹${totalAmount.toLocaleString()}</td>
                        </tr>
                    </tbody>
                </table>

                <div class="footer">
                    <p>Generated by Kwiq Billing App</p>
                </div>
            </body>
            </html>
        `;

        const { uri } = await Print.printToFileAsync({ html });
        await Sharing.shareAsync(uri, { UTI: '.pdf', mimeType: 'application/pdf' });
    } catch (error) {
        console.error('PDF Share Error:', error);
        Alert.alert('Failed to generate PDF');
    } finally {
        isSharing = false;
    }
};

/**
 * Converts an array of objects to CSV string
 */
export const convertToCSV = (data) => {
    if (!data || data.length === 0) return '';

    const headers = Object.keys(data[0]);
    const csvRows = [];

    // Add headers
    csvRows.push(headers.join(','));

    // Add data rows
    for (const row of data) {
        const values = headers.map(header => {
            const val = row[header];
            const escaped = ('' + val).replace(/"/g, '""');
            return `"${escaped}"`;
        });
        csvRows.push(values.join(','));
    }

    return csvRows.join('\n');
};

/**
 * Exports data to CSV and triggers sharing dialog (Excel compatible)
 */
export const exportToExcel = async (data, filename = 'export.csv') => {
    try {
        const csvString = convertToCSV(data);
        const fileUri = FileSystem.documentDirectory + filename;

        await FileSystem.writeAsStringAsync(fileUri, csvString, {
            encoding: FileSystem.EncodingType.UTF8,
        });

        if (!(await Sharing.isAvailableAsync())) {
            Alert.alert('Sharing is not available on this device');
            return;
        }

        await Sharing.shareAsync(fileUri);
    } catch (error) {
        console.error('Export error:', error);
        Alert.alert('Failed to export data');
    }
};
